disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Òrtabels"

[params]
displayName = "FR"
isoCode = "fr"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_ortabels_notitle.png"
description = "L’Ortabels est un lieu de partage, dédié au maraîchage sur sol vivant et à l’agroécologie."

[params.author]
  links = [ ]

["params.author"]
name = "Òrtabels"
headline = "Association"
bio = ""
