[[main]]
none = "none"

[[main]]
name = "Projets"
pageRef = "projets"
identifier = "V0PUZHk4T4"
weight = 1


[[main]]
name = "Contact"
pageRef = "contact"
identifier = "sN7eWLbU2a"
weight = 3

[[main]]
name = ""
pre = "facebook"
url = "https://www.facebook.com/"
identifier = "AsPwTA5qym"
weight = 9_999

[[footer]]
none = "none"
